---
- name: check if we have gnome-extensions
  shell: |
    gnome-extensions --version
  register: cmd
  ignore_errors: yes

- name: install extensions
  include_tasks: install.yml
  when: cmd.rc == 0
