---
- name: Import zoom rpm gpg key
  ansible.builtin.rpm_key:
    state: present
    key: https://zoom.us/linux/download/pubkey?version=5-12-6
    fingerprint: 59C86188E22ABB19BD5540477B04A1B8DD79B481
  become: yes

- name: install zoom from rpm files (latest)
  dnf:
    name: 'https://cdn.zoom.us/prod/5.15.5.5603/zoom_x86_64.rpm'
    state: present
  become: yes
