---
- name: install rpm fusion free repo
  include_role:
    name: install_rpm_with_key
  vars:
    rpm_key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"
    rpm_key_fingerprint: E9A4 91A3 DE24 7814 E7E0 67EA E06F 8ECD D651 FF2E
    rpm_package:
    - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: install rpm fusion nonfree repo
  include_role:
    name: install_rpm_with_key
  vars:
    rpm_key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"
    rpm_key_fingerprint: 79BD B88F 9BBF 7391 0FD4 095B 6A2A F961 9484 3C65
    rpm_package:
    - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
