---
- hosts: localhost
  connection: local
  become: false
  tasks:
    - name: "running role: {{ item }}"
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ running_roles }}"
