#+Startup: showall
* home-config-ansible
Workstation setup scripts. All roles (except the private one) are now migrated to [[https://github.com/novicecpp/mygalaxy][My (Ansible) Galaxy]].
** Prerequisite
- Packages
  #+begin_src text
    - git
    - sudo
    - ssh and ssh-agent
    - sudo
  #+end_src
- Credentials directory
- Local account with =sudo= no password (Or use =init/sudoer.sh=)
** Bootstrap (manual)
*** Create =myhome= directory.
#+begin_src bash
mkdir ~/myhome
#+end_src
Note: I do not back up the whole home directory, but put everything into =~/myhome= instead to clean up the mess left by applications when reinstalling the OS.
*** Symlink/copy credentials path-to-keys directory.
#+begin_src bash
CREDENTIALS_BACKUPPATH=/path/to/backup/creds
CREDENTIALS_PATH=/path/to/credentials-store
cp $CREDENTIALS_BACKUPPATH $CREDENTIALS_PATH
#+end_src
*** Add github ssh key to =ssh-agent= to pull this repository.
#+begin_src bash
  CREDENTIALS_PATH=/path/to/credentials-store
  SSH_KEY="${CREDENTIALS_PATH}/path-to-ssh-key"
  eval "$(ssh-agent)"
  ssh-add -f "${CREDENTIALS_PATH}"
  # adding ssh config
  cat > ~/.ssh/config <<-EOF
  Host github.com
      HostName github.com
      User git
      IdentityFile $SSH_KEY
  EOF
#+end_src
*** Clone this repo and initialize [[https://github.com/novicecpp/home-config-ansible-private][home-config-ansible-private]], [[https://github.com/novicecpp/mygalaxy][mygalaxy]].
#+begin_src bash
cd ~/myhome
git clone git@github.com:novicecpp/home-config-ansible.git
cd home-config-ansible
git submodule update --init
# install galaxy deps and symlink mygalaxy to ~/.ansible
bash mygalaxy/install.sh
#+end_src
*** Clone [[https://github.com/novicecpp/home-config][home-config]] and [[https://github.com/novicecpp/home-config-private][home-config-private]] to =~/myhome=.
#+begin_src bash
cd ~/myhome
git clone git@github.com:novicecpp/home-config.git
cd home-config
git submodule update --init
#+end_src
*** Install pyenv/venv and ansible
#+begin_src bash
cd ~/myhome/home-config-ansible
bash init/pyenv.sh
#+end_src
*** Run home-config-ansible
#+begin_src bash
cd ~/myhome/home-config-ansible
source .venv/bin/activate # sourcing venv
bash example_run.sh  # Switch playbook and inventory to the machine you run in the script.
#+end_src
*** Run home-config setup
TBD
** Note
*** When updating "linux-firmware", you need to do "cold boot".
For Lenovo X1/P1 Gen 2,
- Remove power cord.
- Restart.
- Open bios menu > Power > Turn of built-in battery.
- wait 5 seconds.
- Plug in power cord, open laptop.
