---
- name: ensure ~/.local/bin directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.local/bin
    - ~/.bash_completion.d

- name: downloads argocd binary
  ansible.builtin.get_url:
    url: https://github.com/argoproj/argo-cd/releases/download/v2.9.0-rc2/argocd-linux-amd64
    dest: ~/.local/bin/argocd
    checksum: sha256:3e18a365ecf57955ff15da892fad83ebb75f79ed24e1b17115e792814b9e0189

- name: chmod
  ansible.builtin.file:
    dest: ~/.local/bin/argocd
    mode: '0755'

- name: get completion
  ansible.builtin.shell: ~/.local/bin/argocd completion bash
  register: shell_argocd_output
  changed_when: false

- name: copy completion to .bash_completion.d
  ansible.builtin.copy:
    content: "{{ shell_argocd_output.stdout }}"
    dest: ~/.bash_completion.d/argocd
    mode: '0644'
