---
- name: ensure ~/.local/bin directory
  file:
    path: ~/.local/bin
    state: directory

- name: downloads argocd binary
  ansible.builtin.get_url:
    url: https://github.com/argoproj/argo-cd/releases/download/v2.9.0-rc2/argocd-linux-amd64
    dest: ~/.local/bin/argocd
    checksum: sha256:3e18a365ecf57955ff15da892fad83ebb75f79ed24e1b17115e792814b9e0189

- name: chmod
  ansible.builtin.file:
    dest: ~/.local/bin/argocd
    mode: '0755'
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_uid }}"
