---
- name: add harshicorp
  command: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
  become: yes

- name: install hashicorp binary
  tags: docker
  dnf:
    name: "{{ hashicorp_client_package }}"
    state: present
  become: yes
