---
- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: noisetorch
  register: tmpdir

- name: clone noisetorch
  ansible.builtin.git:
    repo: 'https://github.com/noisetorch/NoiseTorch'
    dest: '{{ tmpdir.path }}'
    single_branch: yes
    version: 7563350d5b2cf6aa206e8132f82c36ab69d9b64c

- name: build
  ansible.builtin.shell:
    cmd: make
    chdir: '{{ tmpdir.path }}'

- name: copy bin to ~/.local/bin
  ansible.builtin.copy:
    src: '{{ tmpdir.path }}/bin/noisetorch'
    dest: ~/.local/bin/noisetorch
    mode: '0755'
    owner: '{{ ansible_user_uid }}'
    group: '{{ ansible_user_uid }}'

- name: set cap to executable
  community.general.capabilities:
    path: '{{ ansible_user_dir }}/.local/bin/noisetorch'
    capability: CAP_SYS_RESOURCE=+ep
    state: present
  become: yes

- name: copy desktop file
  ansible.builtin.copy:
    src: '{{ tmpdir.path }}/assets/noisetorch.desktop'
    dest: ~/.local/share/applications
    mode: '0644'
    owner: '{{ ansible_user_uid }}'
    group: '{{ ansible_user_uid }}'

- name: ensure local user icon dirs
  ansible.builtin.file:
    path: ~/.local/share/icons/hicolor/256x256/apps
    state: directory
    mode: '0755'

- name: copy icon
  ansible.builtin.copy:
    src: '{{ tmpdir.path }}/assets/icon/noisetorch.png'
    dest: ~/.local/share/icons/hicolor/256x256/apps
    mode: '0644'
    owner: '{{ ansible_user_uid }}'
    group: '{{ ansible_user_uid }}'
  notify: reload icon cache
