---
- name: Upgrade all packages
  dnf:
    name: '*'
    state: latest
  become: yes
  register: res
  retries: 3


- name: install fedora package
  dnf:
    name: "{{ fedora_package }}"
    state: present
  become: yes
  register: res
  retries: 3

- name: install rpmfusion package
  dnf:
    name: "{{ rpmfusion_package }}"
    state: present
  become: yes
  register: res
  retries: 3
