---
- name: add flathub to flatpak repo
  tags: flatpak
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: install flatpak package
  tags: flatpak
  flatpak:
    name: '{{ item }}'
    method: user
    state: present
  with_items: '{{ flatpak_package }}'
