---
- name: downloads helm
  include_role:
    name: download_and_extract
  vars:
    download_url: https://get.helm.sh/helm-v3.11.0-linux-amd64.tar.gz
    checksum: sha256:6c3440d829a56071a4386dd3ce6254eab113bc9b1fe924a6ee99f7ff869b9e0b
    path:
      - src: linux-amd64/helm
        dest: ~/.local/bin/

- name: export helm bash completion
  command: bash -c 'helm completion bash > ~/.bash_completion.d/helm.bash'
