- name: install kubectl
  tags: kubectl
  include_role:
    name: download_and_extract
  vars:
    download_url: https://dl.k8s.io/v1.26.1/kubernetes-client-linux-amd64.tar.gz
    checksum: sha512:d82f8fb12b3667c9c613092ac8c5c38c2f0db2db719f8d8b308f1146ef4ac2942b66554fc99ddc1e947492f4cec845a21feebbf804289173c42928a2d355490f
    path:
      - src: kubernetes/client/bin/
        dest: ~/.local/bin

- name: ensure user bash_completion.d dir
  file:
    path: ~/.bash_completion.d
    state: directory

- name: export kubectl bash completion
  command: bash -c 'kubectl completion bash > ~/.bash_completion.d/kubectl.bash'

- name: install kubelogin
  include_role:
    name: download_and_extract
  vars:
    download_url: https://github.com/int128/kubelogin/releases/download/v1.22.1/kubelogin_linux_amd64.zip
    checksum: sha256:dfbc8a6535178f58c2d96bd8d1061d4688de8c83eb1cae9d0db687224ebc6726
    path:
      - src: kubelogin
        dest: ~/.local/bin/kubectl-oidc_login
