- name: install kubectl
  tags: kubectl
  include_role:
    name: download_and_extract
  vars:
    download_url: https://dl.k8s.io/v1.28.3/kubernetes-client-linux-amd64.tar.gz
    checksum: sha256:b7b44a3e8c2587e2d517ddc4d024f4263582758ff52fffab2e08276986914cb6
    path:
      - src: kubernetes/client/bin/
        dest: ~/.local/bin

- name: ensure user bash_completion.d dir
  file:
    path: ~/.bash_completion.d
    state: directory

- name: export kubectl bash completion
  command: bash -c 'kubectl completion bash > ~/.bash_completion.d/kubectl.bash'

- name: install kubelogin
  include_role:
    name: download_and_extract
  vars:
    download_url: https://github.com/int128/kubelogin/releases/download/v1.28.0/kubelogin_linux_amd64.zip
    checksum: sha256:83282148fcc70ee32b46edb600c7e4232cbad02a56de6dc17e43e843fa55e89e
    path:
      - src: kubelogin
        dest: ~/.local/bin/kubectl-oidc_login
