---
- name: downloads kustomize
  include_role:
    name: download_and_extract
  vars:
    download_url: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.2.1/kustomize_v5.2.1_linux_amd64.tar.gz
    checksum: sha256:88346543206b889f9287c0b92c70708040ecd5aad54dd33019c4d6579cd24de8
    path:
      - src: kustomize
        dest: ~/.local/bin/

- name: export kustomize bash completion
  command: bash -c 'kustomize completion bash > ~/.bash_completion.d/kustomize.bash'
