---
- name: ensure ~/.local/bin directory
  file:
    path: ~/.local/bin
    mode: '0755'
    recurse: yes
    state: directory
- name: install k8s components
  include_tasks: "{{ item }}.yml"
  with_items: "{{ k8s_client_components }}"
