---
- name: import rpmfusion free key
  rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
    fingerprint: E9A4 91A3 DE24 7814 E7E0 67EA E06F 8ECD D651 FF2E
  become: yes

- name: import rpmfusion nonfree key
  rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
    fingerprint: 79BD B88F 9BBF 7391 0FD4 095B 6A2A F961 9484 3C65
  become: yes

- name: install rpmfusion free and nonfree
  dnf:
    name:
    - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-34.noarch.rpm
    - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-34.noarch.rpm
    state: present
  become: yes
