---
- name: import key
  rpm_key:
    state: present
    key: "{{ rpm_key }}"
    fingerprint: "{{ rpm_key_fingerprint }}"
  become: yes
  when: rpm_key is defined

- name: install rpm
  dnf:
    name: '{{ rpm_package }}'
    state: present
  become: yes
