pip_package:
- boto3
- ipython
- pipenv
- poetry
- sshuttle
- yapf
- yq
- glances
- docker-compose
- aws2-wrap
- black
- jedi-language-server
- pylint
- flake8
- bandit
- yamllint
- PyYAML
#- pyyaml
- wheel
## cern
- 'python-openstackclient==5.2.0'
- 'python-magnumclient==3.0.1'
- 'keystoneauth1[kerberos]'
