---
- name: Import zoom rpm gpg key
  ansible.builtin.rpm_key:
    state: present
    key: https://zoom.us/linux/download/pubkey
  become: yes

- name: Install the nginx rpm from a remote repo
  dnf:
    name: 'https://zoom.us/client/latest/zoom_x86_64.rpm'
    state: present
  become: yes
