---
- set_fact:
    _git_dir: '{{ git_url | basename }}'
- name: "clone {{ git_url }}"
  git:
    repo: '{{ git_url }}'
    dest: '~/Downloads/{{ _git_dir }}'
    version: master
    depth: 1
- name: 'copy with rsync to {{ to_path }}'
  command: 'rsync -av ~/Downloads/{{ _git_dir }}/{{ from_path }} {{ to_path }}'
