---
- name: ensure has desktop directory
  file:
    path: ~/.local/share/applications/
    state: directory

- name: list all file in local/share/applications/
  find:
    path: '{{ playbook_dir }}/roles/files/local/share/applications'
    recurse: no
    file_type: file
  register: desktop_files

- name: symlink copy scripts
  file:
    src: '{{ item.path }}'
    dest: '~/.local/share/applications/{{ item.path | basename }}'
    state: link
  with_items: "{{ desktop_files.files }}"
