---
- name: downloads pyenv
  include_role:
    name: download_and_extract
  vars:
    download_url: https://github.com/pyenv/pyenv/archive/refs/tags/v2.3.1.tar.gz
    checksum: sha256:adf687597fc103180e6262667f8f3edaaacde298ee689de9bbdeed0f0b8e3efc
    path:
      - src: 'pyenv-2.3.1/'
        dest: '~/.local/share/pyenv'

#- name: download pyenv-virtualenv
#  include_role:
#    name: download_and_extract
#  vars:
#    download_url: https://github.com/pyenv/pyenv-virtualenv/archive/refs/tags/v1.1.5.tar.gz
#    checksum: sha256:27ae3de027a6f6dccdca4085225512e559c6b94b31625bd2b357a18890a1e618
#    from_path: 'pyenv-virtualenv-1.1.5/'
#    to_path: '~/.local/share/pyenv/plugins/pyenv-virtualenv'
