---
- name: install nvidia driver
  dnf:
    name:
    - akmod-nvidia
    - xorg-x11-drv-nvidia-cuda
    state: present
  become: yes

# fix xorg with intel stutter when disable laptops display
- name: check if it x11 session
  command: ./cmd/find_session_type.sh
  register: reg

- name: make nvidia as primary gpu
  copy:
    src: etc/X11/xorg.conf.d/10-nvidia.conf
    dest: /etc/X11/xorg.conf.d/10-nvidia.conf
  when: reg.stdout == 'x11'
  become: yes
