---
- name: ensure fonts dir
  file:
    path: ~/.local/share/fonts
    state: directory

- name: download liberation-mono font
  include_role:
    name: download_and_extract
  vars:
    download_url: https://www.fontsquirrel.com/fonts/download/liberation-mono
    from_path: '*.ttf'
    to_path: ~/.local/share/fonts/

- name: download all-the-icons fonts
  include_role:
    name: download_and_extract
  vars:
    download_url: https://github.com/domtronn/all-the-icons.el/archive/refs/tags/4.0.1.tar.gz
    checksum: sha256:30ac8a44efdf638e893b9f802cde3388da8776d39296dcc83694720ba74950d0
    from_path: 'all-the-icons.el-4.0.1/fonts/*.ttf'
    to_path: ~/.local/share/fonts

- name: refresh front cache
  command: fc-cache -v -f
