---
- name: add docker repo
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  become: yes
- name: install docker
  dnf:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present
  become: yes
- name: add user to docker group
  command: usermod -aG docker "{{ ansible_user_id }}"
  become: yes
