---
- name: downloads pyenv
  include_role:
    name: download_and_extract
  vars:
    download_url: https://github.com/pyenv/pyenv/archive/refs/tags/v2.3.16.tar.gz
    checksum: sha256:699d6d87df08428bcd51ce2523a1dba18827a30bef4aea6fdd138935f2a875df
    path:
      - src: 'pyenv-2.3.16/'
        dest: '~/.local/share/pyenv'

- name: symlink pyenv to ~/.local/bin
  ansible.builtin.file:
    src: '~/.local/share/pyenv/bin/pyenv'
    dest: '~/.local/bin/pyenv'
    owner: "{{ ansible_user_gid }}"
    group: "{{ ansible_user_gid }}"
    state: link

#- name: download pyenv-virtualenv
#  include_role:
#    name: download_and_extract
#  vars:
#    download_url: https://github.com/pyenv/pyenv-virtualenv/archive/refs/tags/v1.1.5.tar.gz
#    checksum: sha256:27ae3de027a6f6dccdca4085225512e559c6b94b31625bd2b357a18890a1e618
#    from_path: 'pyenv-virtualenv-1.1.5/'
#    to_path: '~/.local/share/pyenv/plugins/pyenv-virtualenv'
