---
# ansible 2 does not have copr built-in module
#- name: enable copr
#  community.general.copr:
#    host: copr.fedorainfracloud.org
#    state: enabled
#    name: zeno/scrcpy
#  become: yes

- name: enable copr
  shell: dnf copr enable zeno/scrcpy -y
  become: yes

- name: install scrcpy
  dnf:
    name: scrcpy
    state: present
  become: yes
