---
- name: downloads fd
  include_role:
    name: download_and_extract
  vars:
    download_url: https://github.com/sharkdp/fd/releases/download/v8.6.0/fd-v8.7.0-x86_64-unknown-linux-gnu.tar.gz
    checksum: sha256:0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5
    path:
      - src: fd-v8.7.0-x86_64-unknown-linux-gnu/fd
        dest: ~/.local/bin/
      - src: fd-v8.7.0-x86_64-unknown-linux-gnu/autocomplete/fd.bash
        dest: ~/.bash_completion.d/
